version: '3'
services:
  zoomcamp-hw:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:${HOME_VOLUME}
      - ${CREDENTIALS}:/home/src/personal-gcp
    restart: on-failure:5